# Generated by Django 5.1.6 on 2025-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BombaHeparina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_paciente", models.CharField(max_length=255)),
                ("peso", models.FloatField()),
                ("volumen", models.FloatField(blank=True, null=True)),
                ("infusion_actual", models.FloatField(blank=True, null=True)),
                ("kptt", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
